<?php
$data = $MyRequest->getRequest();
if($MyFrankyMonster->MySeccion() == CATALOG_SEARCH_DEPARTAMENTO)
{
  
  $_departamento      = $MyRequest->getUrlParam('departamento');
  $_categoria      = $MyRequest->getRequest('categoria',[]);
  $_subcategoria      = $MyRequest->getRequest('subcategoria',[]);
  $BuscadorLateralForm->setAtributo('action',$MyRequest->url(CATALOG_SEARCH_DEPARTAMENTO,['departamento' => $_departamento]));

}

elseif($MyFrankyMonster->MySeccion() == CATALOG_SEARCH_CATEGORY)
{
  
  $_categoria      = $MyRequest->getUrlParam('categoria');
  $_departamento   = $MyRequest->getUrlParam('departamento');
  $_subcategoria      = $MyRequest->getRequest('subcategoria',[]);
  $BuscadorLateralForm->setAtributo('action',$MyRequest->url(CATALOG_SEARCH_CATEGORY,['categoria' => $_categoria,'departamento' => $_departamento]));

}
else if($MyFrankyMonster->MySeccion() == CATALOG_SEARCH_SUBCATEGORY)
{
   
  $_categoria      = $MyRequest->getUrlParam('categoria');
  $_subcategoria      = $MyRequest->getUrlParam('subcategoria');
  $_departamento      = $MyRequest->getUrlParam('departamento');
  $BuscadorLateralForm->setAtributo('action',$MyRequest->url(CATALOG_SEARCH_SUBCATEGORY,['categoria' => $_categoria,'subcategoria' => $_subcategoria,'departamento' => $_departamento]));
}
else{
  $_categoria      = $MyRequest->getRequest('categoria',[]);
  $_subcategoria      = $MyRequest->getRequest('subcategoria',[]);
  $_departamento      = $MyRequest->getRequest('departamento',[]);
}


if(!empty($_categoria) && !is_array($_categoria))
{
  $_categoria = [$_categoria];
}
if(!empty($_subcategoria) && !is_array($_subcategoria))
{
  $_subcategoria = [$_subcategoria];
}
if(!empty($_departamento) && !is_array($_departamento))
{
  $_departamento = [$_departamento];
}


$precio	= $MyRequest->getRequest('precio');
$precio_rango = catalog_getPriceMaxMinProduct();
if(!empty($precio))
{
    $precio = explode("-", $precio);
    if(is_array($precio))
    {
        $precio[0] = intval(preg_replace('/[^0-9]+/', '',  $precio[0]), 10);
        $precio[1] = intval(preg_replace('/[^0-9]+/', '', $precio[1]), 10);
    }
}






?>
<?php echo $BuscadorLateralForm->openTag(); ?>
<?php $BuscadorLateralForm->setData($data); ?>
    <?php  echo $BuscadorLateralForm->get("q"); ?>
     <div class="btn_filters"></div>
    <div class="cont_filter">

    <ul>
        <li>
          <label for="amount"><span class="title_filter"><?=_catalog('Precio')?></span></label>
            <?php  echo $BuscadorLateralForm->get("precio"); ?>
          <span class="w-xxxx-12 w-xxx-12 w-xx-12 w-x-12" id="slider-range"></span>
        </li>


        <?php if(!in_array($MyFrankyMonster->MySeccion(), [CATALOG_SEARCH_SUBCATEGORY])): ?>
                    
          <li class="area_categoria">
          <?php  if(!empty($categorias)):?>
                <ul>
                <?php foreach($categorias['cat_0'] as $departamento): ?>
                
                    <?php if(in_array($MyFrankyMonster->MySeccion(), [CATALOG_SEARCH_DEPARTAMENTO,CATALOG_SEARCH_CATEGORY,CATALOG_SEARCH_SUBCATEGORY])  && $departamento['url_key'] != $_departamento[0]) { continue; } ?>
                    
                    <li id="cat_<?=$departamento['id']; ?>">
                      <label>
                      <?php if(!in_array($MyFrankyMonster->MySeccion(), [CATALOG_SEARCH_DEPARTAMENTO,CATALOG_SEARCH_CATEGORY,CATALOG_SEARCH_SUBCATEGORY]) ): ?>
                        <input type="checkbox" name="departamento[]" value="<?=$departamento['url_key']; ?>" <?=(in_array($departamento['url_key'],$_departamento) ? "checked=\"checked\"" : "")?> /> 
                      <?php endif; ?>
                      <?=$departamento['name']; ?> </label>
                        <?php  if(isset($categorias['cat_'.$departamento['id']])):?>
                            <ul>
                            <?php foreach($categorias['cat_'.$departamento['id']] as $categoria): ?>
                
                              <?php if(in_array($MyFrankyMonster->MySeccion(), [CATALOG_SEARCH_CATEGORY,CATALOG_SEARCH_SUBCATEGORY]) && $categoria['url_key'] != $_categoria[0]) { continue; } ?>
                   
                                <li id="cat_<?=$categoria['id']; ?>" ><label>
                                    <?php if(!in_array($MyFrankyMonster->MySeccion(), [CATALOG_SEARCH_CATEGORY,CATALOG_SEARCH_SUBCATEGORY]) ): ?>
                                    <input type="checkbox" name="categoria[]" value="<?=$categoria['url_key']; ?>" <?=(in_array($categoria['url_key'],$_categoria) ? "checked=\"checked\"" : "")?> /> 
                                    <?php endif; ?>
                                    <?=$categoria['name']; ?> </label>
                                    <?php  if(isset($categorias['cat_'.$categoria['id']])):?>
                                        <ul>
                                        <?php foreach($categorias['cat_'.$categoria['id']] as $subcategoria): ?>
                
                    
                                            <li id="cat_<?=$subcategoria['id']; ?>"  ><label><input type="checkbox" name="subcategoria[]" value="<?=$subcategoria['url_key']; ?>" <?=(in_array($subcategoria['url_key'],$_subcategoria) ? "checked=\"checked\"" : "")?> /> <?=$subcategoria['name']; ?></label></li>
                                            
                                        <?php endforeach; ?>
                                        </ul>
                                    <?php endif; ?>
                                </li>
                                
                            <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </li>
                    
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
          </li>
          <?php endif; ?>
        

     
    </ul>
    </div>
 <?php echo $BuscadorLateralForm->endTag(); ?>

 <script>
   var time_event_search = null;
   var ejecutaBusqueda = function(){
      $.ajax({
                       type: 'GET',
                       url: $("form[name=buscadorLateral]").attr('action'),
                       data: $("form[name=buscadorLateral]").serialize(),
                       cache: false,
                       beforeSend: function(){

                           var loader = $('<div>').attr('id',"preloaderfullpageAjaxSearch").css({position: 'fixed',top:0,left:0,right:0, bottom:0,'z-index': 100});
                          loader.append($('<div>').attr('style',window.loaderStyle));

                           $('body').prepend(loader);
                           $('body').css({'overflow':'hidden'});

                       },
                       success: function(response){
                           $("._body").html(response);
                           if($('#preloaderfullpageAjaxSearch'))
                           {
                               $('#preloaderfullpageAjaxSearch').fadeOut('slow',function(){
                                   $(this).remove();
                                   $('body').css({'overflow':'visible'});
                               });

                           }
                       },
                       error: function(){
                         if($('#preloaderfullpageAjaxSearch'))
                         {
                           $('#preloaderfullpageAjaxSearch').fadeOut('slow',function(){
                               $(this).remove();
                               $('body').css({'overflow':'visible'});
                           });

                         }
                         _alert("Error de peticion AJAX","Error"); }
               });

   };
     $(document).ready(function(){
        $("form[name=buscadorLateral]").find("input[type=checkbox]").change(function(){
          if(time_event_search != null)
          {
            clearTimeout(time_event_search);
          }
          time_event_search = setTimeout(function(){
            ejecutaBusqueda();
          }, 3000);
          
        })

        $( "#slider-range" ).slider({
            range: true,
            min:  <?=$precio_rango[0]; ?>,
            max: <?=$precio_rango[1]; ?>,
            values: [ <?=(isset($precio[0]) ? $precio[0] : $precio_rango[0]); ?>, <?=(isset($precio[1]) ? $precio[1] : $precio_rango[1]); ?> ],
            stop: function( event, ui ) {
              if(time_event_search != null)
              {
                clearTimeout(time_event_search);
              }
              time_event_search = setTimeout(function(){
                ejecutaBusqueda();
              }, 3000);
            },
            slide: function( event, ui ) {
              $( "#filtro_precio" ).val(getFormatoPrecio(ui.values[ 0 ],true,'<?=DATA_STORE_CONFIG['simbolo']?>','<?=DATA_STORE_CONFIG['abreviatura']?>') + " - " + getFormatoPrecio(ui.values[ 1 ],true,'<?=DATA_STORE_CONFIG['simbolo']?>','<?=DATA_STORE_CONFIG['abreviatura']?>') );
            }
          });
          $( "#filtro_precio" ).val( getFormatoPrecio($( "#slider-range" ).slider( "values", 0 ),true,'<?=DATA_STORE_CONFIG['simbolo']?>','<?=DATA_STORE_CONFIG['abreviatura']?>') +
            " - " + getFormatoPrecio($( "#slider-range" ).slider( "values", 1 ),true,'<?=DATA_STORE_CONFIG['simbolo']?>','<?=DATA_STORE_CONFIG['abreviatura']?>') );
     });
 </script>
