
<div class="w-xxxx-12">
    <div class="content">
        <h1 class="align_center"></h1>
        <h3 class="align_center"></h3>
        <?php echo $adminForm->openTag(); ?>
        <?php  echo $adminForm->get("callback"); ?>


        <?php if(!empty($id)): ?>
        <?php  echo $adminForm->get("id"); ?>
          <?php endif; ?>
        <?php  echo $adminForm->getRow("nombre"); ?>
         <?php  echo $adminForm->getRow("titulo"); ?>
        <div class="form-group">
          <h3>Categorias</h3>
         
          <div id="jstree">
            
            <ul>
                <li id="cat_0" >Root
                    <?php  if(!empty($categorias)):?>
                    <ul>
                    <?php foreach($categorias['cat_0'] as $departamento): ?>
                    
                        
                        <li id="cat_<?=$departamento['id']; ?>"  <?=(in_array($departamento['id'], $data['category']) ? "data-jstree='{ \"selected\" : true }'": '')?>> <?=$departamento['name']; ?> (ID:<?=$departamento['id']; ?>)
                            <?php  if(isset($categorias['cat_'.$departamento['id']])):?>
                                <ul>
                                <?php foreach($categorias['cat_'.$departamento['id']] as $categoria): ?>
                    
                        
                                    <li id="cat_<?=$categoria['id']; ?>" <?=(in_array($categoria['id'], $data['category']) ? "data-jstree='{ \"selected\" : true }'": '')?>> <?=$categoria['name']; ?> (ID:<?=$categoria['id']; ?>)
                                        <?php  if(isset($categorias['cat_'.$categoria['id']])):?>
                                            <ul>
                                            <?php foreach($categorias['cat_'.$categoria['id']] as $subcategoria): ?>
                    
                        
                                                <li id="cat_<?=$subcategoria['id']; ?>" <?=(in_array($subcategoria['id'], $data['category']) ? "data-jstree='{ \"selected\" : true }'": '')?> > <?=$subcategoria['name']; ?> (ID:<?=$subcategoria['id']; ?>)</li>
                                                
                                            <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </li>
                                    
                                <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>
                        </li>
                        
                    <?php endforeach; ?>
                    </ul>
                    <?php endif; ?>
                </li>
            </ul>
            
        </div>
        <div style="overflow:hidden;width:1px; height:1px;">
        <?php  echo $adminForm->getRow("category[]"); ?>
        </div>
        <label id="category[]-error" class="error" for="category[]" style="display:none;"></label>
        <label id="subcategory[]-error" class="error" for="subcategory[]" style="display:none;"></label>
        </div>
        <div>
            <a href="#" class="open_relacionar">Catalogo de Productos</a>
        </div>
     

        <?php  echo $adminForm->getRow("random"); ?>

        <?php  echo $adminForm->getRow("numero"); ?>

        <?php  echo $adminForm->getRow("guardar"); ?>

        <?php echo $adminForm->endTag(); ?>

    </div>

  

</div>

<div id="relacionar_overlay"  class="overlay w-xxxx-12">
      
       <div class="overlay-content">
       <div class="w-xxxx-6 cont_photo galeria" >
           <div class="clear">&nbsp;</div>
       </div>
       <div class="lightbox_home_error_message">
        
        <a href="javascript:void(0)" class="cerrar_x" onclick="cerrarOverlayRelacionar()">&times;</a>
           <div class="w-xxxx-12 bkg_message_home">


               <iframe id="iframe_relacionar" src="" frameborder="0" width="80%"></iframe>


            </div>
       </div>
   </div>
</div>

<script >
$(document).ready(function()
{
  $( "#frmvitrina" ).validate();
  
  $('input[name="category[]"]').change(function(){
      if($(this).is(':checked'))
      {
        
        $(this).parents('li').children('ul').show();
      }
      else{
        $(this).parents('li').children('ul').hide().find('input[type=checkbox]').prop('checked',false);
      }
  });
});
</script>


<script>
var abrirOverlayRelacionar = function(){
   $("#iframe_relacionar").attr('src','<?=$MyRequest->url(FRM_CATALOG_VITRINA_RELACIONADOS);?>?id=<?=$data['id']?>&amp;callback=<?=$_callback?>').css({'height':($(window).height()*0.8)});
  $("#relacionar_overlay").css({'height':'100%'}).fadeTo(1000,1);
  $("body").addClass("no_scroll");
}

var cerrarOverlayRelacionar = function() {

      $("#relacionar_overlay").fadeTo(1000,0,function(){
          $(this).css({'height':'0%'})
      });

      $("#iframe_relacionar").attr('src','');

      $("body").removeClass("no_scroll");
};
$('.open_relacionar').click(function(e){
    e.preventDefault();
    abrirOverlayRelacionar();
});
 $(document).keyup(function(event){

        if(event.which==27)
        {
            if($("#relacionar_overlay").is(":visible"))
            {
                cerrarOverlayRelacionar();
            }
            
        }
    });


    $('#jstree').on('changed.jstree', function (e, data) {
    var i, j, r = [];
    $('input[name="category[]"]').prop('checked',false);
    for(i = 0, j = data.selected.length; i < j; i++) {
      
      $('input[name="category[]"][value="'+data.instance.get_node(data.selected[i]).id.replace('cat_','')+'"]').prop('checked',true);
      for(k = 0, l = +data.instance.get_node(data.selected[i]).parents.length; k < l; k++) {
        $('input[name="category[]"][value="'+data.instance.get_node(data.selected[i]).parents[k].replace('cat_','')+'"]').prop('checked',true);
      }
    }
    
  }).jstree({
    'checkbox': {
        three_state: false,
        cascade: 'up'
    },
  "plugins" : [ "checkbox" ]
});
</script>