<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?> </div>
        <div class="w-xxxx-12 cont_global_admin">
            <div class="w-xxxx-12 cont_header_panel">
                <div class="_wrapp_form_serch">
                  
                    <a href="<?=$Tokenizer->decode($_callback)?>" class="_btn_new">Regresar</a>
                </div>
            </div>
            <h1 class="titulo_seccion_admin"><?= _('Productos relacionados')?> de <?=$producto_actual['name']?></h1>

            <div  class="w-xxxx-12 cont_productos_relacionados">
                <table id="jqGridRel"></table>
                <div id="jqGridPagerRel"></div>
            </div>
        </div>
 
        <h1 class="titulo_seccion_admin">Otros productos</h1>

        <div class="w-xxxx-12 cont_global_admin">
            <div class="w-xxxx-12 cont_header_panel">
                <div class="_wrapp_form_serch">
                    <form name="buscarGrid" action="" method="get" id="paginar">                
                        <div class="form-group form_buscar"><input type="submit" name="buscar" class="_btn _primary" id="btsSearchGridAdmin" value="Buscar"></div>
                    </form>
                </div>
            </div>
        </div>
        <div  class="w-xxxx-12 cont_gral_admin relacionados">
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
</div>

<script type="text/javascript">
window.parentId = '<?=$MyRequest->getRequest('id')?>';
window.path = '<?=$MyRequest->link($path)?>';
window.pathRel = 'admin/catalog-products/relacionados_actual.php'; 
window.query = '&id=<?=$MyRequest->getRequest('id')?>';
</script>
<script >
$(window).load(function(){
    var isGridMobile = ($(window).width() <= 767 ? true : false);

    $("#jqGrid").GridAdmin({
        search : true,
        entity : 'catalog_rel'+window.query,
        redirectOnSelectRow:false,
        gridPager : "#jqGridPager",
        btnSearch: "#btsSearchGridAdmin",
        redirectPath : '',
        pathData : window.path,
        error : "<?=_('No hay productos registrados')?>",
        callbackFuncion : "relateProducts",
        colModel: [
            { label: '<?=_('ID BACK')?>', name: 'id', key:true, hidden:true, width: 50 },
            { label: '<?=_('STATUS BACK')?>', name: 'status', hidden:true, width: 50 },
            { label: '<?=_('STORE ID')?>', name: 'store_id', hidden:true,  width: 50 },
            { label: '<?=_('ID')?>', name: '_id', hidden:isGridMobile, width: 100 },
            { label: '<?=_('Thumb')?>', name: 'images', hidden:isGridMobile, width: 100, search:false },
            { label: '<?=_('Nombre')?>', name: 'name', width: 250 },
            { label: '<?=_('SKU')?>', name: 'sku', width: 250 },
            { 
            name: 'acciones', 
            index: 'acciones', 
            width: 200, 
            align: 'center', 
            sortable: false, 
            search: false,
            formatter: creadorDeBotones // Vincula la función que creamos en el paso 2
            }
        ],
        subGrid: isGridMobile,
        subGridRowExpanded: showChildGrid,
        width:920
    });

    $("#jqGridRel").GridAdmin({
        search : false,
        entity : 'catalog_rel_true'+window.query,
        redirectOnSelectRow:false,
        gridPager : "#jqGridPagerRel",
        btnSearch: "",
        redirectPath : '',
        pathData : window.pathRel,
        error : "<?=_('No hay productos relacionados')?>",
        callbackFuncion : "relateProducts2",
        colModel: [
            { label: '<?=_('ID BACK')?>', name: 'id', key:true, hidden:true, width: 50 },
            { label: '<?=_('STATUS BACK')?>', name: 'status', hidden:true, width: 50 },
            { label: '<?=_('STORE ID')?>', name: 'store_id', hidden:true,  width: 50 },
            { label: '<?=_('ID')?>', name: '_id', hidden:isGridMobile, width: 100 },
            { label: '<?=_('Thumb')?>', name: 'images', hidden:isGridMobile, width: 100, search:false },
            { label: '<?=_('Nombre')?>', name: 'name', width: 250 },
            { label: '<?=_('SKU')?>', name: 'sku', width: 250 },
            { 
            name: 'acciones', 
            index: 'acciones', 
            width: 200, 
            align: 'center', 
            sortable: false, 
            search: false,
            formatter: creadorDeBotones2 // Vincula la función que creamos en el paso 2
            }
        ],
        subGrid: isGridMobile,
        subGridRowExpanded: showChildGrid,
        width:920
    });
 });

 function creadorDeBotones(cellvalue, options, rowObject) {
    
    var id = options.rowId; // Obtiene el ID único de la fila actual

    var boton = '<a class="btn_adm_relacionar btn_adm_relacionar_product_mp_switch " data-id="'+id+'" href="#'+rowObject.status+'"></a>';

   
    return boton;
}

function showChildGrid(parentRowID, parentRowKey) {
    var childGridID = parentRowID + "_table";
    var childGridPagerID = parentRowID + "_pager";
    
    if($(window).width() <= 767) {
      
        var id  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_:id"]').text();
        var thumb  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_images"]').html();
        var type  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_type"]').text();
        var store  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_store"]').text();
      
        $('#' + parentRowID).append('<p>ID: '+id+'</p>');
        $('#' + parentRowID).append('<p>Thumb: '+thumb+'</p>');
       
    }
}
function relateProducts() {
    $.fn.buttonDelete('a.btn_adm_relacionar_product_mp_switch')
    
    $(".btn_adm_relacionar").click(function(event){
        event.preventDefault();
        var nuevo_estado = ($(this).attr("href").replace("#","") == "activar" ? 1 : 0);
        if(nuevo_estado == 1) {
            ajax_products_agregarProductoRelacionado(window.parentId ,$(this).attr('data-id'))
        } else {
            ajax_products_quitarProductoRelacionado(window.parentId ,$(this).attr('data-id'))
        }
        
    });
}

function creadorDeBotones2(cellvalue, options, rowObject) {
    
    var id = options.rowId; // Obtiene el ID único de la fila actual

    var boton = '<a class="btn_adm_relacionar_ btn_adm_relacionar_product_mp_switch2" data-id="'+id+'" href="#'+rowObject.status+'"></a>';

   
    return boton;
}

function relateProducts2() {
    $.fn.buttonDelete('a.btn_adm_relacionar_product_mp_switch2')
    
    $(".btn_adm_relacionar_").click(function(event){
        event.preventDefault();
        var nuevo_estado = ($(this).attr("href").replace("#","") == "activar" ? 1 : 0);
        if(nuevo_estado == 1) {
            ajax_products_agregarProductoRelacionado(window.parentId ,$(this).attr('data-id'))
        } else {
            ajax_products_quitarProductoRelacionado(window.parentId ,$(this).attr('data-id'))
        }
        
    });
}

</script>
