
        <?php echo $adminForm->openTag(); ?>
        <?php echo $adminForm->getRow('parent_id'); ?>
        <?php echo $adminForm->getRow('status'); ?>
        <?php if(!empty($id)): ?>
        <?php echo $adminForm->getRow('id'); ?>
        <?php endif; ?>
        <?php echo $adminForm->getRow('activar'); ?>
        <?php echo $adminForm->getRow('name'); ?>
        
        <?php echo $adminForm->getRow('description'); ?>

        <?php echo $adminForm->getRow('visible_in_search'); ?>
        <?php echo $adminForm->getRow('users[]'); ?>
        <div id="imagen_previa">
            <?php if(!empty($data['image'])): ?>
              <?=makeHTMLImg($data['image'], "", "", "");?>
            <?php endif; ?>
        </div>
        <?php echo $adminForm->getRow('image'); ?>
        <div class="form-group"><h3>SEO</h3></div>
        <?php echo $adminForm->getRow('url_key'); ?>
        <?php echo $adminForm->getRow('meta_title'); ?>
        <?php echo $adminForm->getRow('meta_description'); ?>
        <?php echo $adminForm->getRow('meta_keywords'); ?>
        <?php echo $adminForm->getRow('guardar'); ?>
        <?php echo $adminForm->endTag(); ?>

   