<?php
$_img = getCoreConfig('catalog/product/placeholder');
$principal = "";
if($_img != "" && file_exists(PROJECT_DIR.$_img))
{
    $img = imageResize($_img,700,700, true);
    $principal =  makeHTMLImg($img,"","",$data_detalle['name'],'id="img_zoom"');
}
?>

<div>
<div class="slider slider-for">
<?php
if(!empty($data_detalle['images']))
{
    foreach($data_detalle["images"] as $foto)
    {
        if($foto['principal'])
        {
            if(!empty($foto["img"]) && file_exists($MyConfigure->getServerUploadDir()."/catalog/products/".$data_detalle["id_ori"].'/'.$foto['img']))
            {
                $img = imageResize($MyConfigure->getUploadDir()."/catalog/products/".$data_detalle["id_ori"].'/'.$foto['img'],700,700, true);
                $imgori = $MyConfigure->getUploadDir()."/catalog/products/".$data_detalle["id_ori"].'/'.$foto['img'];
                echo makeHTMLImg($img,"","",$data_detalle['name'],'id="img_zoom" data-large="'.$imgori.'" data-scale="2" data-share="" class="thumb_gal" ');
            }
            else
            {
                echo $principal;
            }
        }

    }
}
else{
    echo $principal;
}
?>
</div>


<?php
if(!empty($data_detalle['images'])   && count($data_detalle['images']) > 1)
{
    ?>
    <div class="slider slider-nav">
    <?php
    foreach($data_detalle["images"] as $foto)
    {
        //  echo $MyConfigure->getServerUploadDir()."/catalog/products/".$data_detalle["id_ori"].'/'.$foto['img'];
        if(!empty($foto["img"]) && file_exists($MyConfigure->getServerUploadDir()."/catalog/products/".$data_detalle["id_ori"].'/'.$foto['img']))
        { ?>
            <div>
            <a href="javascript:void(0);" onclick="setImgZoom('<?=imageResize($MyConfigure->getUploadDir()."/catalog/products/".$data_detalle["id_ori"].'/'.$foto['img'],700,700, true)?>','<?= $MyConfigure->getUploadDir()."/catalog/products/".$data_detalle["id_ori"].'/'.$foto['img']?>')">
            <?=makeHTMLImg(imageResize($MyConfigure->getUploadDir()."/catalog/products/".$data_detalle["id_ori"].'/'.$foto['img'],100,100, true),"","",$data_detalle['name']);?>
            </a>
            </div>
        <?php
        }
    }
    ?>
    </div>
    <?php
}
?>

</div>

<script>
  $(document).ready(function(){
          $('.slider-nav').slick({
            slidesToShow: 4,
            slidesToScroll: 4,
            //asNavFor: '.slider-for',
            dots: false,
            centerMode: true,
            focusOnSelect: true
          });
  });
  var  setImgZoom= function(img, large)
  {
      $('#img_zoom').attr('src',img);
      $('#img_zoom').attr('data-large',large);
      
  }
  $('img.thumb_gal').fullscreenimage()
    
</script>
