<?php if(getCoreConfig('catalog/marketplace/enabled') == 1 && $MyAccessList->MeDasChancePasar("solicitud_user_marketplace")): ?>
<div class="_cont_dashboard _perfil">
  <div class="w_100 cont_admin_redes">
    <div  class="form-group form-inline">
      <h3>Marketplace</h3>
      <div><a href="<?=$MyRequest->url(SOLICITUD_USER_MARKETPLACE)?>" title="" class="_btn _secondary">Quiero convertirme en vendedor</a></div>
    </div>
  </div>
  </div>
<?php endif; ?>