<div class="w-xxxx-12">
    <div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?> </div>
        <h1 class="align_center"></h1>
        <h3 class="align_center"></h3>
        <?php echo $adminForm->openTag(); ?>
        <?php  echo $adminForm->get("callback"); ?>


        <?php if(!empty($id)): ?>
        <?php  echo $adminForm->get("id"); ?>
          <?php endif; ?>
          <?php  echo $adminForm->getRow("parent_id"); ?>
          <?php  echo $adminForm->getRow("name"); ?>
          <?php  echo $adminForm->getRow("description"); ?>
          <div id="content_attrs"></div>
        
        <?php  echo $adminForm->getRow("guardar"); ?>
        <?php echo $adminForm->endTag(); ?>
    </div>
</div>

<script>
$(document).ready(function()
{
  $( "#frmsetatributos" ).validate();
  
});


$('select[name="parent_id"]').change(function(){
  ajax_getCatalogSetAttr('<?= $id ?>');
});
ajax_getCatalogSetAttr('<?= $id ?>');
</script>